//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationId { get; set; }
        public string LAddressLine1 { get; set; }
        public string LState { get; set; }
        public string LCity { get; set; }
        public string LCountry { get; set; }
        public Nullable<int> LPincode { get; set; }
    }
}
